const express=require('express')
const Router=express.Router()
const Admin = require('../Controllers/AdminController')
const AdminMiddl= require('../Middlerwares/AdminMiddle')
const AdminFileMiddl= require('../Middlerwares/AdminFileMiddl')
const ChatMidll= require('../Middlerwares/MiddleForChat')

Router.post('/addActu',AdminMiddl,AdminFileMiddl,Admin.addActu)
      .put('/updateActu',AdminMiddl,Admin.updateActu)
      .post('/deleteActu',AdminMiddl,Admin.deleteActu)
      .get('/getDepts',AdminMiddl,Admin.getDepts)
      .post('/addDept',AdminMiddl,Admin.addDept)
      .post('/addFil',AdminMiddl,Admin.addFil)
      .post('/addClasse',AdminMiddl,Admin.addClasse)
      .post('/addModule',AdminMiddl,Admin.addModule)
      .post('/updateDept',AdminMiddl,Admin.updateDept)
      .post('/updateFil',AdminMiddl,Admin.updateFil)
      .post('/updateClasse',AdminMiddl,Admin.updateClasse)
      .post('/updateModule',AdminMiddl,Admin.updateModule)
      .post('/deleteDept',AdminMiddl,Admin.deleteDept)
      .post('/deleteFil',AdminMiddl,Admin.deleteFil)
      .post('/deleteClasse',AdminMiddl,Admin.deleteClasse)
      .post('/deleteModule',AdminMiddl,Admin.deleteModule)
      .post('/approuveEtu',AdminMiddl,Admin.approuveEtu)
      .post('/modifyEtu',AdminMiddl,Admin.modifyEtu)
      .post('/deleteEtu',AdminMiddl,Admin.deleteEtu)
      .post('/approuveProf',AdminMiddl,Admin.approuveProf)
      .post('/editProf',AdminMiddl,Admin.editProf)
      .get('/getChats/:id',ChatMidll,Admin.getChats)
      .get('/getModuleForChat/:idMod',ChatMidll,Admin.getModule)
      .get('/getUsersForChat/:id',ChatMidll,Admin.getUsersForChat) 
      .get('/getUsersForChatOneToOne/:id',ChatMidll,Admin.getUsersForChatAdmin)
      .post('/getChatsForAdmin',ChatMidll,Admin.getChatsAdmin)

module.exports=Router